# Generated by Django 4.2.3 on 2024-05-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aftosalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brent', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=10)),
                ('rang', models.CharField(max_length=10)),
                ('yil', models.IntegerField(max_length=4)),
                ('narx', models.FloatField()),
                ('quvati', models.IntegerField()),
            ],
        ),
    ]
